### ISSUE TITLE
Referenced library security-crypto-ktx:1.1.0 does not exist (yet)

### ISSUE THREAD

**Issue by mpost** [osipxd/encrypted-datastore#11]
The README references the `security-crypto-ktx:1.1.0` which does not exist yet. the 1.1.0 stream is currently at alpha04.

**Comment by osipxd** [comment]
Nice point! I should mention it in README, thank you

**Comment by osipxd** [comment]
Added warning to README
<img width="808" alt="image" src="https://user-images.githubusercontent.com/3684355/208605749-fcf8d889-627b-486b-887b-6cbb77a9a223.png">
