### ISSUE TITLE
Please add a simple example of storing/retrieving a value using this library, in the readme?

### ISSUE THREAD

**Issue by RowanG-IAG** [osipxd/encrypted-datastore#17]

**Comment by osipxd** [comment]
You can use encrypted DataStore just as a normal DataStore, so usage is the same as described in the [official DataStore docs](https://developer.android.com/topic/libraries/architecture/datastore). [Here](https://developer.android.com/topic/libraries/architecture/datastore#preferences-read) you can find examples for Preference DataStore and [here](https://developer.android.com/topic/libraries/architecture/datastore#proto-read) is for "Proto" DataStore.

**Comment by osipxd** [comment]
@RowanG-IAG, is my answer enough for you? I'm going to close this issue due to inactivity.

**Comment by RowanG1** [comment]
I feel that the serializer could benefit from a readme entry. Basically, a full simple example could save users a lot of looking/confirming.

**Comment by osipxd** [comment]
Currently I haven't enough time to add full sample, but I've added link to official samples to README: https://github.com/osipxd/encrypted-datastore/commit/efbb0118b1dde5f02cf02739643e5be5c942d765
