### ISSUE TITLE
Version for datastore 1.1.0

### ISSUE THREAD

**Issue by osipxd** [osipxd/encrypted-datastore#9]
DataStore 1.1.0 contains [breaking changes](https://developer.android.com/jetpack/androidx/releases/datastore#1.1.0-alpha01): 
- Exposed PreferencesSerializer, previously it was internal
- Library is multiplatform now, so it may require changes on my side

**Comment by phazei** [comment]
Any plans on updating this for 1.1.0?

**Comment by osipxd** [comment]
Yes, I plan to finish this before `datastore` goes into beta

**Comment by osipxd** [comment]
[datastore:1.1.0-beta01 is out](https://developer.android.com/jetpack/androidx/releases/datastore#1.1.0-beta01)

**Comment by osipxd** [comment]
Ouch. datastore 1.1.0 is already here.

**Comment by osipxd** [comment]
Version [1.1.1-beta01](https://github.com/osipxd/encrypted-datastore/releases/tag/v1.1.1-beta01) is out. With datastore 1.1.1 as a dependency.
